<?php namespace View; Use _; ?>
<p><a href="index.html">[index]</a> <a href="<?=url('comment/'.$link)?>">[permalink]</a> <a href="https://twitter.com/search?f=tweets&q=lwbrd<?=$issue?>&src=typd" target="_blank">[comment]</a></p>

<header>
<?=align('lowb1rd.github.io', $formattedDate)."\n";?>
<span style="clear: both;"><?=$formattedTags?></span>
Blog Entry: <?=$issue?>
</header>

<article>
    <h1><?=$title?></h1>
<?=$content?>

    <footer><p>--<br />(c) <?=date('Y');?> Nils Kraemer, last modified: <?=date('Y-m-d', $datetime);?></p></footer>
    <aside>
        <h1>Comments</h1>
        <p>Comments are on Twitter, use Hashtag <a href="https://twitter.com/search?f=tweets&q=lwbrd<?=$issue?>&src=typd" target="_blank">#lwbrd<?=$issue?></a> to leave a comment.</p>
    </aside>
</article>
