<?php namespace View; Use _; ?>
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="utf-8" />
    <title><?=ifset($title, 'lowb1rd.github.io')?></title>

    <link rel="alternate" type="application/rss+xml" title="RSS-Feed lowb1rd.github.io" href="<?=url('feed.xml')?>" />

    <meta name="description" content="" />
	  <meta name="viewport" content="width=320, initial-scale=1, shrink-to-fit=no" />

    <style>
      body {
        max-width: 620px;
      }
      body, p, h1, h2 {
          font-family: monospace;
          font-size: 13px;
      }
      h1 {
          xletter-spacing: 4px;
          text-align: center;
          margin-bottom: 2em;
      }
      .pre, header {
          white-space: pre;
      }
      article, aside {
          padding-top: 2em;
          padding-bottom: 2em;
      }
      p {
          margin-left: 3em;
          margin-right: 1em;
      }
      article pre, div.pre {
          margin-left: 5em;
      }
      article a {
          text-decoration: none;
      }
      article aside h1 {
          text-align: left;
          letter-spacing: 5px;
          margin-bottom: 1em;
      }
      article footer {
          color: #666;
      }
      .flr {
        float: right;
      }
    </style>
</head>
<body>

<?$T->render()?>

</body>
</html>
